/******************************************************************************/
/****         Generated by IBExpert 2005.08.08 20/4/2007 10:14:58          ****/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1252;

CREATE DATABASE 'C:\Infra\UnitTests\InfraHibernate\DBDEMOS.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 4096
DEFAULT CHARACTER SET WIN1252;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE ACCOUNT (
    ID              INTEGER NOT NULL,
    ACCOUNTNUMBER   VARCHAR(18) CHARACTER SET WIN1252,
    ACCOUNTNAME     VARCHAR(18) CHARACTER SET WIN1252,
    INITIALBALANCE  NUMERIC(18,2),
    CURRENTBALANCE  NUMERIC(18,2)
);


INSERT INTO ACCOUNT (ID, ACCOUNTNUMBER, ACCOUNTNAME, INITIALBALANCE, CURRENTBALANCE) VALUES (1, '1361-2', 'BB 1361', 125.3, 1524.25);
INSERT INTO ACCOUNT (ID, ACCOUNTNUMBER, ACCOUNTNAME, INITIALBALANCE, CURRENTBALANCE) VALUES (2, '1111-3', 'CEF 1111', NULL, NULL);
INSERT INTO ACCOUNT (ID, ACCOUNTNUMBER, ACCOUNTNAME, INITIALBALANCE, CURRENTBALANCE) VALUES (3, '5454-9', 'BRADESCO 5454', NULL, 1030);

COMMIT WORK;



/******************************************************************************/
/****                             Primary Keys                             ****/
/******************************************************************************/

ALTER TABLE ACCOUNT ADD PRIMARY KEY (ID);


/******************************************************************************/
/****                               Indices                                ****/
/******************************************************************************/

CREATE UNIQUE DESCENDING INDEX XPKACCOUNT ON ACCOUNT (ID);
